Firefox ignores addTransceiver init setEncodings opts
webrtcHacks/adapter pull request #1004
Opened 2019-08-01 17:10 UTC by kekkokk

should fix https://github.com/webrtcHacks/adapter/issues/998

2019-08-01 21:11 UTC, jan-ivar approved these changes
Awesome, thanks!

2019-08-01 21:11 UTC, jan-ivar commented on src/js/firefox/firefox_shim.js
> +          initParameters.sendEncodings.forEach((encodgingParam) => {
Typo. `s/encodgingParam/encodingParam/`

2019-08-01 21:11 UTC, jan-ivar commented on src/js/firefox/firefox_shim.js
> +                .catch(() => Promise.resolve())
Nit: `.catch(() => {})` implicitly converts to a promise, so create one is redundant.

2019-08-01 21:11 UTC, jan-ivar commented on src/js/firefox/firefox_shim.js
> +          if (sender) {
Nit: redundant `if`. All transceivers have a sender.

2019-08-01 21:11 UTC, jan-ivar commented on src/js/firefox/firefox_shim.js
> +      return Promise.all(setParametersPromises)
Looks good, except I think I'd prefer to add the following lines directly ahead of the above line:
```js
if (!setParametersPromises.length) {
  return origCreateOffer.apply(this, arguments);
}
```
That way we only disturb the timing of *createOffer*'s synchronous validation steps when necessary (mostly an [[IsClosed]] test). It's really only observable in the debugger (Promise appears <rejected> in console immediately), but still.

It'd make me feel better if we didn't disturb the timing of *every* createOffer out there.

2019-08-01 21:13 UTC, jan-ivar commented
I guess *technically* we'd want to do this in *createAnswer* too?

2019-08-02 04:17 UTC, fippo commented on src/js/firefox/firefox_shim.js
> +  // https://github.com/webrtcHacks/adapter/issues/998#issuecomment-516921647
what the test caught here is a missing
```
  if (!(typeof window === 'object' && window.RTCPeerConnection)) {
    return;
  }
```

2019-08-02 04:17 UTC, fippo commented on src/js/firefox/firefox_shim.js
> +          if (sender) {
also: const {sender} = transceiver;

2019-08-02 04:17 UTC, fippo commented on src/js/firefox/firefox_shim.js
> +                sender.setParameters({encodings: initParameters.sendEncodings})
you need to set params.encodings and then call setParameters. setParameters should reject but doesn't in Firefox.
Do we need more here like maxBitrate?

2019-08-02 04:17 UTC, fippo commented on src/js/firefox/firefox_shim.js
> +  if (origCreateOffer) {
if you add the same "does RTCPeerConnection exist" check  as above  you can skip this check

2019-08-02 04:19 UTC, fippo commented on src/js/firefox/firefox_shim.js
> +let setParametersPromises = [];
doesn't this need to be per peerconnection, i.e. pc._setParametersPromises? Otherwise we create dependencies between peerconnections

2019-08-02 10:32 UTC, kekkokk commented
Thanks guys for the suggestions. I reviewed all your points with my colleague @simonemazzoni
I also implemented it for the createanswer but I wasn't really able to test so any help would be appreciated.

2019-08-02 10:34 UTC, kekkokk commented on src/js/firefox/firefox_shim.js
> +                sender.setParameters({encodings: initParameters.sendEncodings})
need some info from @jan-ivar for this topic

2019-08-02 10:37 UTC, kekkokk commented on src/js/firefox/firefox_shim.js
> +let setParametersPromises = [];
Totally right, I did not think about it and I thought that was not a nice thing to "inject" parameters in the PeerConnection if possible. But in this case I think is the only solution

2019-08-02 14:27 UTC, fippo commented
I wonder if we should have a e2e test along the lines of:
1) call pc.addTransceiver with a video track and sendEncodings
2) call pc.createOffer()
3) check that the offer contains an a=simulcast line.

We would need to make testable in Chrome too since that is how the e2e tests work... but Chrome generates different SDP (slightly)

2019-08-02 16:08 UTC, kekkokk commented
Tried to implement a basic e2e test, never did this so be patient. Feel free to rewrite from scratch
thanks @fippo

2019-08-02 17:57 UTC, fippo commented on test/e2e/simulcast.js
> +      this.skip();
this isn't defined in arrow functions (the general recommendation is not to use arrow functions but...) so you'll need to make the it a regular function.

2019-08-02 17:57 UTC, fippo commented on test/e2e/simulcast.js
> +    var constraints = {video: true};
const

2019-08-02 17:57 UTC, fippo commented on test/e2e/simulcast.js
> +            {'rid': 'high'},
{rid: 'high'} et al

2019-08-02 17:57 UTC, fippo commented on test/e2e/simulcast.js
> +      .then(function(stream) {
arrow function please

2019-08-02 17:57 UTC, fippo commented on test/e2e/simulcast.js
> +            {'rid': 'low', 'scaleResolutionDownBy': 3}
i think you need 4 here?

2019-08-02 17:57 UTC, fippo commented on test/e2e/simulcast.js
> +      .catch(throwError);
I think instead of the done-throwError you can return a promise chain from GUM to createOffer and the result of this last check

2019-08-02 18:38 UTC, jan-ivar commented on src/js/firefox/firefox_shim.js
> +                sender.setParameters({encodings: initParameters.sendEncodings})
Yeah that line deviated from what I suggested in https://github.com/webrtcHacks/adapter/issues/998#issuecomment-516921647 but I didn't flag it, because this code would only ever run in a Firefox without a proper *setParameters* implementation, so it seemed fine. 

That said, @fippo is right the following would be more correct (avoids suppressing other init options outside of encodings for no reason—Firefox just doesn't support any of them atm):
```js
setParameters(Object.assign({}, init, {encodings: initParameters.sendEncodings}))
```

`maxBitrate` is already part of [RTCRtpEncodingParameters](https://w3c.github.io/webrtc-pc/#dom-rtcrtpencodingparameters) so we should be good there.

2019-08-02 18:40 UTC, jan-ivar commented on src/js/firefox/firefox_shim.js
> +let setParametersPromises = [];
Good catch! I missed that.

2019-08-02 18:44 UTC, jan-ivar commented on src/js/firefox/firefox_shim.js
> +let setParametersPromises = [];
> I thought that was not a nice thing to "inject" parameters in the PeerConnection if possible

Could we maybe modify the patch to create it on-demand, i.e. only if `sendEncodings` is actually used?

2019-08-05 11:08 UTC, kekkokk commented on test/e2e/simulcast.js
> +            {'rid': 'low', 'scaleResolutionDownBy': 3}
Seems that setting to 4 breaks chrome 77 dev.
Did we found a bug? XD

I tried to also make a GUM in 1080p but it gives me only the first 3 layers in 77 dev.

2019-08-05 11:33 UTC, kekkokk commented on test/e2e/simulcast.js
> +            {'rid': 'low', 'scaleResolutionDownBy': 3}
seems that Webrtc is switching from a max of 4 to a max of 3 in m77

[m75](https://chromium.googlesource.com/external/webrtc/+/branch-heads/m75/api/video/video_codec_constants.h)

[m77](https://chromium.googlesource.com/external/webrtc/+/branch-heads/m77/api/video/video_codec_constants.h)

so... idk. I revert the tests from 4 to 3?

2019-08-10 00:35 UTC, jan-ivar approved these changes
This looks great! Did it stall?

2019-08-10 00:35 UTC, jan-ivar commented on test/e2e/simulcast.js
> +});
Add newline.

2019-08-11 06:57 UTC, fippo commented
no, now its blocked by chrome canary failing for some reason. Arguably that is unrelated to Firefox so...

2019-08-12 14:21 UTC, kekkokk commented
Yeah seems that new webrtc codebase does not accept more than 3 layers, so it fails on canary. 
https://github.com/webrtcHacks/adapter/pull/1004#discussion_r310560149

How do we proceed?

2019-08-13 07:41 UTC, fippo commented
yeah, lets go for 3 layers and 2/4 scaledown

@orphis: you might want to check the above is intended if anyone uses this.

2019-08-13 15:44 UTC, Orphis commented on test/e2e/simulcast.js
> +            {'rid': 'low', 'scaleResolutionDownBy': 3}
We're not really switching, the 4th layer would never be used because of some internal limiting of simulcast layer count. Trying to remove that limitation showed that the 4th one was unusable for other reasons, so we properly limit it to 3 now (until we fix the other issue).

2019-08-13 15:46 UTC, Orphis commented on test/e2e/simulcast.js
> +            {rid: 'low', scaleResolutionDownBy: 4}
libwebrtc doesn't support more than 3 simulcast layers, and so does Chrome. You should probably reduce the layer count here.

2019-08-13 15:49 UTC, Orphis requested changes
You should only use 3 simulcast layers in your test at most.

2019-08-15 10:38 UTC, fippo commented
>           /a=simulcast:[\s]?send (?:rid=)?original;high;medium;low/g;
One last thing to push it over the finish line :-)

2019-08-15 22:11 UTC, kekkokk commented
> > ```
> >       /a=simulcast:[\s]?send (?:rid=)?original;high;medium;low/g;
> > ```
> 
> One last thing to push it over the finish line :-)

sorry @fippo I'm on holidays and i lost connection until now. I was using my phone and the github web editor XD

2019-08-16 07:00 UTC, merged

2019-08-16 07:01 UTC, fippo commented
will publish 7.3.0 soonish. Enjoy your vacation!