util: fix wrapPeerConnection
webrtcHacks/adapter pull request #1036
Opened 2020-05-20 07:39 UTC by fippo

so it doesn't blindly assume that the handler is a function
Fixes #1034

Test Plan:
```
class Test {
    constructor() {
        this.pc = new RTCPeerConnection({ iceServers: [{ urls: 'stun:stun.l.google.com:19302' }] })
        this.pc.addEventListener('negotiationneeded', this)
        this.pc.createDataChannel('data')
    }
    close() {
        this.pc.removeEventListener('signalingstatechange', this)
        this.pc.close()
    }
    handleEvent(evt) {
        console.log('Received event', evt)
    }
}
const t = new Test(); t.pc.createOffer().then(offer => t.pc.setLocalDescription(offer))
```
shows 'Received event negotiationneeded'

2020-05-20 07:41 UTC, fippo commented
I think this isn't going to work fully since _eventMap indexes by cb which will be the same object. Probably needs to index by [cb, eventname] but that was broken before.

2020-05-25 11:31 UTC, fippo commented
@jan-ivar can you review?

2020-05-26 15:34 UTC, jan-ivar requested changes

2020-05-26 15:34 UTC, jan-ivar commented on src/js/utils.js
> +    this._eventMap[eventNameToWrap].push([cb, wrappedCallback]);
Good riddance of the old code here, since objects used as keys in regular objects get [turned into strings](https://jsfiddle.net/jib1/ra4nuL32/), which means that the old code would not have distinguished between identical-looking functions that were nonetheless different objects. In contrast, a `Map` would let us use objects as indexes directly (with proper object comparison).

Good call to map things _per name_, to catch reusing the same handler on different topics. The array stuff looks accurate enough, but feels like a poor-man's re-implementation of `Map`, so I'd recommend just using `Map` instead—it's implemented in [all browsers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Browser_compatibility) by now. E.g.
```js
    if (!this._eventMap[eventNameToWrap]) {
      this._eventMap[eventNameToWrap] = new Map();
    }
    this._eventMap[eventNameToWrap].set(cb, wrappedCallback);
```
In fact, I worry that the array version has subtly different semantics if add/remove is [called several times with the same listener](https://jsfiddle.net/jib1/nu1abc5e/).

2020-05-29 14:04 UTC, fippo commented
updated!

2020-06-13 19:58 UTC, jan-ivar approved these changes
⭐⭐⭐⭐⭐

2020-06-14 06:42 UTC, merged