Firefox: do not attempt to modify read-only property in ice candidate shim
webrtcHacks/adapter pull request #1123
Opened 2023-02-22 21:50 UTC by fippo

fixes #1122

2023-02-22 22:09 UTC, jan-ivar requested changes

2023-02-22 22:09 UTC, jan-ivar commented on src/js/common_shim.js
> +      augmentedCandidate.prototype = nativeCandidate.prototype;
`nativeCandidate.prototype` is `undefined` here so this won't work.

I'd prefer not to mess with prototypes and instead modify and return the real platform object. This should work:
```js
    const nativeCandidate = new NativeRTCIceCandidate(args);
    const parsedCandidate = SDPUtils.parseCandidate(args.candidate);
    for (const key in parsedCandidate) {
      nativeCandidate[key] = parsedCandidate[key];
    }
```

2023-02-22 22:09 UTC, jan-ivar commented on src/js/common_shim.js
> +      augmentedCandidate.prototype = nativeCandidate.prototype;
The above should provide parity with existing code. If we want to match spec, we'd add read-only properties:
```js
    const nativeCandidate = new RTCIceCandidate(options);
    const parsedCandidate = SDPUtils.parseCandidate(options.candidate);
    for (const key in parsedCandidate) {
      if (!(key in nativeCandidate)) {
        Object.defineProperty(nativeCandidate, key, {value: parsedCandidate[key]});
      }
    }
```

2023-02-23 08:29 UTC, fippo commented on src/js/common_shim.js
> +      augmentedCandidate.prototype = nativeCandidate.prototype;
That is better indeed! I wonder if the native Firefox toJSON would do the right thing out of the box but technically this code path can still be hit very *very* old Chrome

2023-02-23 09:06 UTC, fippo commented
Sadly the patch doesn't apply clean to v7 or v6 (that one is still ES5) but it is easy enough to backport.

2023-02-23 14:12 UTC, jan-ivar commented on src/js/common_shim.js
> +      // Override serializer to not serialize the extra attributes.
Hmm, this should be unnecessary, since [enumerable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#enumerable) defaults to `false`. Did it not work in ES5? If the default changed, does the following help?
```js
Object.defineProperty(nativeCandidate, key, {
  value: parsedCandidate[key],
  enumerable: false
});
```

2023-02-23 14:15 UTC, jan-ivar commented on src/js/common_shim.js
> +      // Override serializer to not serialize the extra attributes.
If anything, [my pilot error](https://github.com/webrtcHacks/adapter/issues/1122#issuecomment-1440795147) was caused by the custom toJSON on the native object persisting, causing me to mistakenly think the properties hadn't been copied, because I was using JSON.stringify to dump things to console in my first fiddle attempts.

2023-02-23 14:19 UTC, jan-ivar commented on src/js/common_shim.js
> +      // Override serializer to not serialize the extra attributes.
To clarify, I believe even with `enumerable: true` I would not expect new properties to appear in JSON, because of the native [toJSON for RTCIceCandidate](https://w3c.github.io/webrtc-pc/#dom-rtcicecandidate-tojson) is already custom and limited.

2023-02-24 07:35 UTC, fippo commented on src/js/common_shim.js
> +      // Override serializer to not serialize the extra attributes.
True but this code still has to deal with the theoretical possibility of Chromes native toJSON predating the right thing

2023-02-27 22:29 UTC, jan-ivar approved these changes

2023-02-27 22:29 UTC, jan-ivar commented on src/js/common_shim.js
> +      // Override serializer to not serialize the extra attributes.
Oh I missed that this was fixing up existing code. LGTM!

2023-03-12 08:25 UTC, merged