test: add mocha/chai for functional testing
webrtcHacks/adapter pull request #404
Opened 2016-12-20 12:55 UTC by fippo

this adds mocha and chai for functional testing.

Far from complete obviously, this is more a discussion starter. Had to make some changes to the chrome shim to make it work outside the browser environment.

2016-12-20 13:04 UTC, fippo commented
Also add [sinon](http://sinonjs.org/) to the mix and then have something like this:
```
window.RTCPeerConnection = sinon.stub();
window.RTCPeerConnection.returns({
                addIceCandidate: sinon.stub().returns(Promise.resolve(mockStatsObject)),
});
```

2016-12-21 08:11 UTC, KaptenJansson commented
Interesting that Mocha and Chai are very similar to [jasmine](https://github.com/webrtc/apprtc/blob/master/src/web_app/js/appcontroller_test.js) ;) I added that to the AppRTC [repo](https://github.com/webrtc/apprtc/blob/master/karma.conf.js)

2016-12-21 14:44 UTC, fippo commented
there is more than one js framework to do it ;-)

2017-01-26 07:46 UTC, KaptenJansson commented
Mocha/Chai LGTM for me. Is there anything else you want to add or should I review as is?

2017-01-26 08:13 UTC, fippo commented
go ahead :-)

2017-01-26 08:23 UTC, KaptenJansson requested changes
Generally looking good, I also think we should update the test instructions at https://github.com/webrtc/adapter/blob/master/test/README.md

2017-01-26 08:23 UTC, KaptenJansson commented on package.json
> +    "mocha": "^3.2.0",
Aren't these dev-dependencies?

2017-01-26 08:23 UTC, KaptenJansson commented on src/js/chrome/chrome_shim.js
> +        return new window.webkitRTCPeerConnection(pcConfig, pcConstraints);
Maybe add a comment at the top of the shim about why we have to include 'window`?

2017-01-26 08:23 UTC, KaptenJansson commented on test/unit/chrome.js
> +const chai = require('chai');
Add the webrtc copyright header with the current year.

2017-01-26 08:23 UTC, KaptenJansson commented on test/unit/chrome.js
> +const expect = chai.expect;
I wonder when we can go es6 all the way ;)

2017-01-26 20:27 UTC, fippo reviewed
thanks. I've added two commits, can squash after re-review

2017-01-26 20:27 UTC, fippo commented on package.json
> +    "mocha": "^3.2.0",
done

2017-01-26 20:27 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +        return new window.webkitRTCPeerConnection(pcConfig, pcConstraints);
hrm. I was too lazy to figure out an excuse so I just set global.window = global ;-)

2017-01-26 20:27 UTC, fippo commented on test/unit/chrome.js
> +const chai = require('chai');
done

2017-01-27 06:49 UTC, fippo commented
hrm. Don't merge yet. I am modifying global.window in one test and this spills over to another. Need to find a way to reset this...

2017-01-27 08:07 UTC, KaptenJansson commented on src/js/chrome/chrome_shim.js
> +        return new window.webkitRTCPeerConnection(pcConfig, pcConstraints);
Nice!

2017-01-27 08:07 UTC, KaptenJansson approved these changes

2017-01-27 08:35 UTC, merged