edge: add RTX
webrtcHacks/adapter pull request #458
Opened 2017-03-04 12:15 UTC by fippo

this adds parsing and serialization for all things RTX
and removes the pieces of code removed rtx from the list of
codecs.

Took a bit longer to test since simplewebrtc was still stuck on adapter 1.x and 2.x deep in the dependencies but... seems to work just fine.

2017-03-04 12:17 UTC, fippo commented on src/js/edge/edge_shim.js
> +  var audioTracks = tracks.filter(function(track) {
this was a whoops. We are still trying to be ES5, right? Then why didn't eslint yell at me...

2017-03-06 10:05 UTC, KaptenJansson requested changes
LGTM with nit

2017-03-06 10:05 UTC, KaptenJansson commented on test/unit/edge.js
> +          videoTrack.kind = 'video';
Why use `const` when you change a property?

2017-03-06 11:10 UTC, fippo commented on test/unit/edge.js
> +          videoTrack.kind = 'video';
const is basically "I am not going to reassign this" -- https://mathiasbynens.be/notes/es6-const
Not like the c++ const "I am not going to change this"

2017-03-06 11:13 UTC, KaptenJansson commented on test/unit/edge.js
> +          videoTrack.kind = 'video';
aha, thanks for clarifying!

2017-03-06 11:13 UTC, KaptenJansson approved these changes

2017-03-06 11:13 UTC, KaptenJansson commented
LGTM

2017-03-06 11:13 UTC, merged