edge: create offers with bundle by default
webrtcHacks/adapter pull request #463
Opened 2017-03-07 20:26 UTC by fippo

creates offers with a a=group:BUNDLE line by default.
Non-bundled offers can be achieved by ѕetting bundlePolicy
to max-compat.

(yes, this was easier than fixing a bug in my usage...)

2017-03-08 13:43 UTC, fippo commented
(still waiting for a edge webdriver version that matches my edge version before I can run the tests)

2017-03-13 07:28 UTC, fippo commented
tests run with one failure (the ice gathering state change test) which is unrelated. ready-to-merge

2017-03-21 08:56 UTC, KaptenJansson requested changes
LGTM

2017-03-21 08:56 UTC, KaptenJansson approved these changes

2017-03-21 08:57 UTC, merged