edge: throw some SLD/SRD state errors
webrtcHacks/adapter pull request #496
Opened 2017-04-10 08:47 UTC by fippo

as described in https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-18#section-5.5
and https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-18#section-5.6

2017-04-12 13:00 UTC, KaptenJansson commented on src/js/edge/rtcpeerconnection_shim.js
> +    if ((description.type === 'offer' &&
For the sake of readability I would say the number of checks are on the limit, WDYT about putting them in a function with a descriptive name that returns a bool?

2017-04-12 13:00 UTC, KaptenJansson commented on src/js/edge/rtcpeerconnection_shim.js
> +    if ((description.type === 'offer' &&
Same as previous comment

2017-04-12 13:47 UTC, fippo commented on src/js/edge/rtcpeerconnection_shim.js
> +    if ((description.type === 'offer' &&
hrm. essentially that should be a function that checks if the state transition is allowed. I like that idea!

2017-04-16 12:17 UTC, fippo commented on src/js/edge/rtcpeerconnection_shim.js
> +    if ((description.type === 'offer' &&
done

2017-05-02 09:12 UTC, fippo commented
@MirkoBonadei can you take a look at this on too? (give me an inch... :-))

2017-05-02 11:23 UTC, MirkoBonadei requested changes
lgtm, just a question about the error message.

2017-05-02 11:23 UTC, MirkoBonadei commented on src/js/edge/rtcpeerconnection_shim.js
> +      var e = new Error('Can not set remote ' + description.type +
I guess the error message should start with: 'Can not set local ', right?

2017-05-02 11:25 UTC, fippo commented on src/js/edge/rtcpeerconnection_shim.js
> +      var e = new Error('Can not set remote ' + description.type +
🦅 👁 

fixed + squashed!

2017-05-02 11:29 UTC, merged