chrome: dirty pc.addTrack
webrtcHacks/adapter pull request #503
Opened 2017-04-13 20:52 UTC by fippo

shims addTrack by creating a new "virtual" stream and adding the track to that.
Future calls to addTrack will add the track to the "virtual" stream and call
removeStream(); addStream() to trigger ONN. This seems to have no visible effect.

alternative to #502 -- less elaborate (aka: doesn't bother to integrate with the senders object yet).
The main disadvantage of this approach is that
1) pc.getLocalStreams() returns different streams than those that were added. Using getLocalStreams and addTrack together seems unlikely.
2) the msid in the SDP is that of the virtual stream, not the stream added. This could be solved with marginal SDP mangling in a createOffer shim.

2017-04-14 07:22 UTC, fippo commented
I've tried SDP mangling in createOffer. However, this means that setLocalDescription will be called with a stream id which Chrome might consider unknown so I don't think this is a good idea.

@henbos @guidou can you take a look? In particular the question above and calling removeStream/addStream in rapid succession?

2017-04-25 11:10 UTC, henbos requested changes

2017-04-25 11:10 UTC, henbos commented on test/test.js
> +      pc1.addTrack(stream.getAudioTracks()[0], stream);
We should still have test coverage for addStream. Perhaps this test should be parameterized for the different ways of adding tracks.

2017-04-25 11:10 UTC, henbos commented on src/js/chrome/chrome_shim.js
> +        RTCPeerConnection.prototype.addStream = function(stream) {
Why are you not shiming addStream if there exists an addTrack? Is the assumption that if addTrack is implemented, addStream will be implemented by using addTrack? Can you add a comment?

2017-04-25 11:10 UTC, henbos commented on src/js/chrome/chrome_shim.js
> +              'The adapter.js addTrack polyfill only supports a single stream.',
Add "... which is associated with the specified track." to cover the OR case of the above if.

If I'm reading the spec correctly, the association between tracks and streams is based on senders internal streams slot, not whether or not the stream contains the track - but based on current implementation, it would be broken if stream didn't. Can you add a comment in an appropriate place?

2017-04-25 11:10 UTC, henbos commented on src/js/chrome/chrome_shim.js
> +                'InvalidAccessError');
This is correct according to spec, but doesn't this imply we can't add a track to a new stream if it has already been added to the peer connection? Even though we can add and remove it from a MediaStream, whatever that means in absence of pc.addTrack or if pc.addTrack was used instead of pc.addStream.

2017-04-25 11:10 UTC, henbos commented on src/js/chrome/chrome_shim.js
> +          }
We should have test coverage both for adding to an existing stream and a new stream?

2017-04-25 11:10 UTC, henbos commented on src/js/chrome/chrome_shim.js
> +            var newStream = new MediaStream([track]);
Why is the streams argument ignored in favor of creating a new MediaStream? Would this work if the streams was an empty list (which we have earlier made sure it isn't by throwing an exception)?

2017-04-25 11:10 UTC, henbos commented on test/test.js
>      navigator.mediaDevices.getUserMedia({audio: true})
In general, I am worried about the lack of test coverage in this PR. addTrack and addStream seem to have a lot of special cases (how was the track added, if added/removed, etc) and RTCPeerConnection contains stuff like stream getters. We should make sure calls can be made, streams are as expected, etc.

2017-04-25 11:14 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +            var newStream = new MediaStream([track]);
because the stream might be a stream containing an audio + video track but only the audio track can be added using addTrack and adding the stream directly would result in both the audio and video track being added

2017-04-25 11:17 UTC, fippo commented on test/test.js
> +      pc1.addTrack(stream.getAudioTracks()[0], stream);
so far this is a strawman. But yes, moar tests are definetly needed.

2017-04-25 11:18 UTC, fippo commented on test/test.js
> +      pc1.addTrack(stream.getAudioTracks()[0], stream);
(and I wonder why i changed the dtmf test...)

2017-04-25 11:54 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +        RTCPeerConnection.prototype.addStream = function(stream) {
odd. I suppose my thinking was "if you want to use getSenders use addTrack". But... the current ocde doesn't make sense.

2017-04-26 04:10 UTC, fippo commented on test/test.js
> +      pc1.addTrack(stream.getAudioTracks()[0], stream);
it turns out i changed it because it broke but now i'm shimming addStream with senders again so this change got reverted

2017-04-26 04:14 UTC, fippo commented on test/test.js
>      navigator.mediaDevices.getUserMedia({audio: true})
what is the minimum test coverage we need?
1) call established + ice up with addTrack, using an audio-video stream
2) call established, ice up but not sending video when using an audio-only stream
3) addTrack with an audio track from streamA and a video track from streamB should result in ontrack with two different streams at the remote end.

2017-04-26 04:56 UTC, fippo commented on test/test.js
>      navigator.mediaDevices.getUserMedia({audio: true})
added tests. I'm not fully happy with them, in particular they don't assert that for case 3 above there are two remote tracks

2017-04-26 04:57 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +          }
is this sufficiently covered by testing with an a/v stream or do we need an audio->audio/video upgrade test?

2017-04-28 08:49 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +                'InvalidAccessError');
@jan-ivar btw, this (copied from you) is es6 and should compare t.track === track

@henbos can you give an example?

2017-04-28 08:54 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +              'The adapter.js addTrack polyfill only supports a single stream.',
hrm. Now you made me wonder if we could have an internal slot in our senders. Might make sense to add that.

Moving forward I assume you'll expose RTCRtpSender together with addTrack?

2017-04-28 16:11 UTC, fippo commented
test failure seems to be due to #508 which is now in beta? :-/

2017-05-02 07:54 UTC, fippo commented
hrm. So github doesn't allow me to say "i have addressed that feedback, please take another look"... @henbos manual ping ;-)

2017-05-04 09:12 UTC, KaptenJansson commented
@henbos ping

2017-05-10 07:19 UTC, fippo commented
ok... so I did a test. And found behaviour I object to :-/
Checkout this, open test/testpage.html

Paste this:
```
var v = document.createElement('video');
v.autoplay = true;
v.id = 'remoteVideo';
document.body.appendChild(v);
var pc1 = new RTCPeerConnection();
var pc2 = new RTCPeerConnection();
var audioStream = null;
pc1.onicecandidate = e => pc2.addIceCandidate(e.candidate);
pc2.onicecandidate = e => pc1.addIceCandidate(e.candidate);
pc2.onaddstream = function(e) { document.getElementById('remoteVideo').srcObject = e.stream; }
navigator.mediaDevices.getUserMedia({audio: true})
.then(stream => {
  audioStream = stream;
  stream.getTracks().forEach(t => {
    sender = pc1.addTrack(t, stream);
    console.log(sender);
  });
  return pc1.createOffer();
})
.then((offer) => {
  return pc2.setRemoteDescription(offer);
})
.then(() => {
  return pc1.setLocalDescription(pc2.remoteDescription);
})
.then(() => {
  return pc2.createAnswer();
})
.then(answer => {
  return pc1.setRemoteDescription(answer);
})
.then(() => {
  return pc2.setLocalDescription(pc1.remoteDescription);
});
```
then paste this
```
navigator.mediaDevices.getUserMedia({video: true})
.then(stream => {
  stream.getTracks().forEach(t => {
    audioStream.addTrack(t);
    sender = pc1.addTrack(t, audioStream);
    console.log(sender);
  });
  return pc1.createOffer();
})
.then((offer) => {
  return pc2.setRemoteDescription(offer);
})
.then(() => {
  return pc1.setLocalDescription(pc2.remoteDescription);
})
.then(() => {
  return pc2.createAnswer();
})
.then(answer => {
  return pc1.setRemoteDescription(answer);
})
.then(() => {
  return pc2.setLocalDescription(pc1.remoteDescription);
});
```
Expected result: the remote video is shown. It is not. getStats say it is received and pasting this actually shows it:
```
remoteVideo.srcObject = pc2.getRemoteStreams()[0]
```

This is fairly easy to work around by unconditionally setting srcObject i ontrack but... I think this has worked in the past and might be a regression from the native srcObject implementation.

2017-05-11 11:35 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +            pc.removeStream(oldStream);
TODO: this is to trigger ONN. Maybe try dispatchEvent(ONN)

2017-05-11 11:43 UTC, henbos approved these changes
LGTM

2017-05-11 15:12 UTC, fippo commented
rebased. Don't merge until we have had a patch release please, this is a minor.

2017-05-15 07:38 UTC, KaptenJansson commented
LGTM

2017-05-15 07:38 UTC, merged