Adding shims for addStream and legacy callback APIs
webrtcHacks/adapter pull request #521
Opened 2017-05-01 04:48 UTC by youennf

**Description**
Adding legacy APIs (addStream) and callback support for setRemoteDescription, setLocalDescription, addIceCandidate, createOffer and createAnswer for Safari.

**Purpose**
Support some legacy websites.

2017-05-01 15:57 UTC, youennf commented
Failing test seems to be selenium-based. Not sure whether this is fine or whether something should be done here.

2017-05-01 16:08 UTC, fippo commented on src/js/safari/safari_shim.js
> +      return Promise.resolve();
that doesn't look right. Shouldn't you return promise?

2017-05-01 16:09 UTC, fippo commented
travis failure is due to #509

2017-05-01 16:17 UTC, fippo commented on src/js/safari/safari_shim.js
> +      var promise = createOffer.apply(this, [arguments[2]]);
I think you need something along the lines of https://github.com/webrtc/adapter/blob/master/src/js/chrome/chrome_shim.js#L297 to pass through the createOffer(offerOptions) stuff here.

2017-05-01 16:55 UTC, youennf commented on src/js/safari/safari_shim.js
> +      return Promise.resolve();
As per https://www.w3.org/TR/webrtc/#legacy-interface-extensions, createOffer step 7says "Return a promise resolved with undefined".
I guess that we should really return void but cannot due to WebIDL limitations, hence the current design.

2017-05-01 16:56 UTC, youennf commented on src/js/safari/safari_shim.js
> +      var promise = createOffer.apply(this, [arguments[2]]);
Right, I'll fix that!

2017-05-01 16:57 UTC, fippo commented on src/js/safari/safari_shim.js
> +      return Promise.resolve();
ah... that makes sense!

2017-05-01 17:44 UTC, jan-ivar requested changes

2017-05-01 17:44 UTC, jan-ivar commented on src/js/safari/safari_shim.js
> +      var promise = createOffer.apply(this, [arguments[2]]);
`options` is the first argument in the promise case, and the third argument in the callback case. This passes up the wrong argument in the promise case.

2017-05-02 09:02 UTC, fippo commented
wrt to unit tests what do you think about this using chai and sinon-chai (happy to make a PR when you're done):
```
  describe('createOffer shim', () => {
    describe('options passing', () => {
      let stub;
      beforeEach(() => {
        stub = sinon.stub();
        window.RTCPeerConnection.prototype.createOffer = stub;
        shim.shimCallbacksAPI();
      });

      it('with no arguments', () => {
        var pc = new RTCPeerConnection();
        pc.createOffer();
        expect(stub).to.have.been.calledWith(undefined);
      });

      it('with two callbacks', () => {
        var pc = new RTCPeerConnection();
        pc.createOffer(null, null);
        expect(stub).to.have.been.calledWith(undefined);
      });

      it('with a non-function first argument', () => {
        var pc = new RTCPeerConnection();
        pc.createOffer(1);
        expect(stub).to.have.been.calledWith(1);
      });

      it('with two callbacks and options', () => {
        var pc = new RTCPeerConnection();
        pc.createOffer(null, null, 1);
        expect(stub).to.have.been.calledWith(1);
      });

      it('with two callbacks and two additional arguments', () => {
        var pc = new RTCPeerConnection();
        pc.createOffer(null, null, 1, 2);
        expect(stub).to.have.been.calledWith(1);
      });
    });
  });
```
I've been wanting to add sinon for stubs for a long time...

2017-05-02 12:02 UTC, fippo approved these changes

2017-05-02 13:17 UTC, MirkoBonadei commented
lgtm

2017-05-02 13:17 UTC, merged

2017-05-02 15:02 UTC, youennf commented
Don't really know chai and sinon-chai. Happy to see how this would look like.