all: add augmenting RTCIceCandidate constructor
webrtcHacks/adapter pull request #527
Opened 2017-05-05 12:39 UTC by fippo

adds an RTCIceCandidate constructor which parses the fields as
described in https://w3c.github.io/webrtc-pc/#rtcicecandidate-interface

2017-05-05 12:40 UTC, fippo commented
hrm... @jan-ivar can you take a look?

2017-05-05 14:42 UTC, fippo commented
hrm. The toJSON stuff doesn't work in Edge :-/

2017-05-05 15:47 UTC, jan-ivar commented
@fippo Hooking up RTCPeerConnection.prototype.addEventListener seems doable.

2017-05-05 16:45 UTC, jan-ivar requested changes
Cool stuff!

2017-05-05 16:45 UTC, jan-ivar commented on src/js/common.js
> +      window.RTCIceCandidate = function(args) {
If there's no window.RTCIceCandidate we're probably on a non-webrtc browser and shouldn't shim anything.

I see you moved this from the edge shim. By the comment there, it seems like a flaw specific to Edge. Maybe it should move back?

2017-05-05 16:45 UTC, jan-ivar commented on src/js/common.js
> +        if (args.candidate.indexOf('a=') === 0) {
I think we should defer input validation to the native class as much as possible. i.e. get out of the way of invalid args, e.g.
```js
if (typeof args === 'object' && typeof args.candidate === 'string' &&
    args.candidate.indexOf('a=') === 0)
```

2017-05-05 16:45 UTC, jan-ivar commented on src/js/common.js
> +        Object.assign(nativeCandidate, parsedCandidate);
This seems to overwrite all props in `nativeCandidate`, making it redundant. Did you mean:
```js
var candidate = Object.assign({}, parsedCandidate, new NativeRTCIceCandidate(args));
```
?

2017-05-05 16:45 UTC, jan-ivar commented on src/js/common.js
> +    if (!window.RTCIceCandidate.prototype.foundation) {
This will give a `TypeError` I think if `.foundation` is ever defined. I.e. `if (!window.RTCIceCandidate.prototype.candidate)` gives me a `TypeError` today.

2017-05-05 16:45 UTC, jan-ivar commented on test/unit/rtcicecandidate.js
> +    it('drops the a= part of the candidate if present', () => {
Is this "drop the `a=` part" feature documented anywhere?

2017-05-05 17:22 UTC, fippo commented on src/js/common.js
> +      window.RTCIceCandidate = function(args) {
I considered so but that would mean I have to call this after the Edge shim. Doable...

2017-05-05 17:36 UTC, fippo commented on src/js/common.js
> +    if (!window.RTCIceCandidate.prototype.foundation) {
right, I need a 'in' here!

2017-05-05 17:38 UTC, fippo commented on test/unit/rtcicecandidate.js
> +    it('drops the a= part of the candidate if present', () => {
both chrome and firefox used to emit ice candidates with a=candidate in the ice candidate event. This has been removed a while back.

Both chrome and edge do this which is wrong imo:
```
var pc = new RTCIceCandidate({candidate: 'a=candidate:foo'})
pc.candidate; // returns a=candidate:foo
```

2017-05-05 18:47 UTC, jan-ivar commented on src/js/common.js
> +            args.candidate.indexOf('a=') === 0) {
As long as you're cool with `new RTCIceCandidate(1)` failing with `TypeError: args.candidate.indexOf is not a function`  in adapter js instead of the built in `TypeError: Argument 1 of RTCIceCandidate.constructor can't be converted to a dictionary.`

2017-05-05 18:50 UTC, jan-ivar commented on src/js/common.js
> +            parsedCandidate);
Works, though `augmentedCandidate` is still just `nativeCandidate` by a different name.

2017-05-05 18:50 UTC, jan-ivar approved these changes
lgtm.

2017-05-05 20:15 UTC, fippo commented
hooked up things in the addEventListener and onicecandidate which makes them useful. Do I need to care about the removeEventListener stuff?

Now I just need to write browser tests to prove this works...

2017-05-06 06:33 UTC, fippo commented
gee. This actually worked out better than I expected!

2017-05-11 12:30 UTC, henbos requested changes

2017-05-11 12:30 UTC, henbos commented on src/js/common.js
> +    if (window.RTCIceCandіdidate && 'foundation' in
Typo!

2017-05-11 12:30 UTC, henbos commented on src/js/common.js
> +      // for legacy reasons.
Problem here is not that it accepts "a=" but that it returns ice candidates with "a=", this is a bug regardless of if we want to accept "a=" or not in the SDP.

Can you change the comment to "Remove the a= which shouldn't be part of the candidate string."

2017-05-11 12:30 UTC, henbos commented on src/js/common.js
> +    // https://w3c.github.io/webrtc-pc/#rtcicecandidate-interface
nit: Capital first letter in all comments.

2017-05-11 12:30 UTC, henbos commented on src/js/common.js
> +    };
Can you move add/removeEventListener to somewhere more generic, outside of shimRTCIceCandidate? I'm imagining if we need to shim non-RTCIceCandidate related things in the future and there being conflicts between the different overrides of addEventListener. (Although these should be chainable so maybe not too bad...)

2017-05-13 08:18 UTC, fippo commented on src/js/common.js
> +    // https://w3c.github.io/webrtc-pc/#rtcicecandidate-interface
in this case i'd argue that "foundation" is a technical term. All other comments fixed though.

2017-05-13 08:59 UTC, fippo commented
@henbos done -- remains to be seen whether we will need to wrap more events but this should work.

2017-05-14 17:19 UTC, fippo commented
It looks like the change of component from string to numeric was something the Edge shim was not ready for yet so i've reverted the changes in the sdp package for now. Will reapply in the future, the fix there is trivial.

2017-05-15 12:13 UTC, henbos approved these changes
lgtm

2017-05-15 12:13 UTC, henbos commented on test/unit/rtcicecandidate.js
> +    expect(Object.keys(JSON.parse(serialized)).length).to.equal(4);
What's the fourth member? Could you add a comment?

2017-05-15 12:24 UTC, fippo commented on test/unit/rtcicecandidate.js
> +    expect(Object.keys(JSON.parse(serialized)).length).to.equal(4);
it should have four members. Will add a commment and then squash!

2017-05-15 12:28 UTC, fippo commented on test/unit/rtcicecandidate.js
> +    expect(Object.keys(JSON.parse(serialized)).length).to.equal(4);
ufrag. Surprised? ;-)

2017-05-15 12:41 UTC, fippo commented
lint failure is because of unrelated merge and new rules. Will fix elsewhere

2017-05-15 18:00 UTC, fippo commented
oh. From "cool but unexpected side-effects": this will make Chrome signal ufrag as part of the top-level object. I think it would be safer to do a major version bump.

2017-05-16 08:18 UTC, KaptenJansson commented
LGTM

2017-05-16 08:18 UTC, merged