chrome: make addTrack + getLocalStreams work
webrtcHacks/adapter pull request #559
Opened 2017-05-19 07:42 UTC by fippo

fix for #557 (hopefully)

2017-05-19 08:53 UTC, henbos commented
I wonder what is the right behavior for getLocalStreams() when streams have been added with addTrack(), see [related discussion about remote streams](https://github.com/w3c/webrtc-pc/issues/1182).

Should a stream return every track that has a sender with that stream? If not, it makes little sense to return streams in getLocalStreams() that have not been added with addStream() or we could return streams that appear to be empty even though a sender has associated that stream with a track. If yes, do we do this only for senders that are currently in use or all senders that exist? What happens if you mix pc.addStream, stream.addTrack, pc.addTrack and sender.replaceTrack behavior...

2017-05-19 10:23 UTC, fippo commented
well, this is the classical example...
```
var pc = new RTCPeerConnection();
navigator.mediaDevices.getUserMedia({audio: true, video: true})
.then((stream) => {
  pc.addTrack(stream.getAudioTracks()[0], stream);
  // what tracks does pc.getLocalStreams()[0] have?
})
```
With this change the answer is consistent with what Firefox returns, a stream with two tracks.

I'm quite worried about mixed use of addStream and addTrack...

2017-05-19 10:29 UTC, henbos commented
Interesting.
```
var pc = new RTCPeerConnection();
navigator.mediaDevices.getUserMedia({audio: true, video: true})
.then((stream) => {
  let audioTrack = stream.getAudioTracks()[0];
  stream.removeTrack(audioTrack);
  pc.addTrack(audioTrack, stream);
  // 1. Is stream.getAudioTracks() empty?
  // 2. What tracks does pc.getLocalStreams()[0] have?
})
```
Does that work? :)

2017-05-19 10:50 UTC, fippo commented
That was throwing (and still does):
```
DOMException: The adapter.js addTrack polyfill only supports a single  stream which is associated with the specified track.
```

2017-05-19 11:17 UTC, fippo commented
we are digressing but...
```
var pc = new RTCPeerConnection();
navigator.mediaDevices.getUserMedia({audio: true, video: true})
.then((stream) => {
  console.log(stream.id);
  let audioTrack = stream.getAudioTracks()[0];
  stream.removeTrack(audioTrack);
  pc.addTrack(audioTrack, stream);
  console.log(stream.getTracks());
})
```
In Firefox stream.getTracks() returns a stream with only a video track.

2017-05-22 11:32 UTC, KaptenJansson commented
@henbos any other thoughts?

2017-05-22 14:13 UTC, fippo commented
(needs minor updates to use window. now)

2017-06-02 11:41 UTC, fippo commented
updated but kept as separate commits in case we want to cherry-pick the first one for a 3.x patch release.

2017-06-09 13:41 UTC, KaptenJansson commented
Ping @henbos

2017-06-12 10:17 UTC, fippo commented
hrm. Something is phishy here. Probably because this uses pc.addStream internally instead of the non-shimmed version.

2017-06-12 10:28 UTC, henbos submitted a review, later dismissed

2017-06-12 10:28 UTC, henbos commented on src/js/chrome/chrome_shim.js
> +        pc._reverseStreams[stream.id] = stream; // consistency with addTrack.
nit: Don't split end-of-line comments into multiple comments, move to above the two lines instead.

2017-06-12 10:28 UTC, henbos commented on test/test.js
> +      pc.addTrack(track, localStream);
Can you verify that pc.getLocalStream still returns a single stream that is localStream after this, and that it has an audio and video track?

2017-06-12 10:29 UTC, henbos commented
Is something not working?

2017-06-12 10:30 UTC, fippo commented
pc._streams contains two members after adding two tracks from the same stream. this is rather unexpected...

2017-06-12 10:31 UTC, henbos commented
Perhaps you should verify _streams etc. in the test as well.

2017-06-12 12:05 UTC, fippo commented
internal apis should only be tested in unit tests. Now there should be unit tests for this, yes... ;-)

2017-06-12 12:10 UTC, fippo commented
@KaptenJansson merging the PRs in that area is going to be a mess. Lets plan to do it on Wednesday

2017-06-14 05:02 UTC, fippo commented
from "weird things that work as expected" for some value of "expected":
```
var localStream;
var pc = new RTCPeerConnection();
var senders1;
var senders2;
navigator.mediaDevices.getUserMedia({audio:true, video: true})
.then(stream => {
  localStream = stream;
  pc.addTrack(stream.getTracks()[0], stream);
  console.log(pc.getLocalStreams()[0].getTracks());
})
```

2017-06-14 07:12 UTC, fippo commented
ugh. So the test failure in chrome beta (with native senders) is highly confusing. It looks like once the track is added to the stream that has been added to the peerconnection, a sender is created:
https://jsfiddle.net/bebhg6ya/
which makes the addTrack shim bail out early since it sees the sender already existing. @henbos ^^

I think I can work around it somehow

2017-06-14 11:20 UTC, fippo commented
going to file a bug about that fiddle because chrome and firefox return different results from createOffer

2017-06-14 11:25 UTC, KaptenJansson commented
@henbos could you PTAL again? Thanks!

2017-06-15 12:46 UTC, fippo commented on src/js/chrome/chrome_shim.js
>              oldStream.addTrack(track);
ironically I am using the behaviour that I find so "bad" here. cc @taylor-b

2017-06-20 08:42 UTC, henbos commented on src/js/chrome/chrome_shim.js
>                  'InvalidAccessError');
'A sender already exists for this track.'

2017-06-20 08:42 UTC, henbos commented on src/js/chrome/chrome_shim.js
> +        if (!pc._reverseStreams[stream.id]) {
Can this happen? The internally created streams are as far as I can tell completely hidden from the external caller (unless the caller is an internal, another part of the shimming).

2017-06-20 08:42 UTC, henbos commented on src/js/chrome/chrome_shim.js
> +                  }
track/dtmf shimming: Can the repeated code be avoided with a helper function?

2017-06-20 08:42 UTC, henbos commented on src/js/chrome/chrome_shim.js
> +      });
Do we really need to shim addTrack etc twice? It's complicated and lots of repeated code. Can we not have a single shim and do if for what is different: "if we have getSenders, return the sender with that track, otherwise return our own sender object", not repeating the code that is shared?

2017-06-20 09:27 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +        if (!pc._reverseStreams[stream.id]) {
the shimmed addTrack uses the shimmed addStream. Pigs fly :-)

2017-06-20 09:29 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +      });
it is a lot of duplication but the alternative was to have a very complicated do-everything :-/

2017-06-20 11:30 UTC, fippo commented on src/js/chrome/chrome_shim.js
>                  'InvalidAccessError');
the spec says "If an RTCRtpSender for track already exists in senders" -- i'd rather keep this close to the spec language

2017-06-20 11:42 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +                  }
done. I also noticed that with native senders we do not support dtmf. Can you consider not making them available until that is hooked up to reduce the complexity? Might be easy to backfill now though...

2017-06-20 14:27 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +                pc._dtmf = null;
@jan-ivar what was the purpose of setting pc._dtmf to null? or did I do the wrong thing here by assuming this === pc?

2017-06-20 14:32 UTC, jan-ivar commented on src/js/chrome/chrome_shim.js
> +                pc._dtmf = null;
@fippo [dtmf](https://w3c.github.io/webrtc-pc/#dom-rtcrtpsender-dtmf) says: *"A null value indicates that this RTCRtpSender cannot send DTMF."* - We can't send DTMF signals on a video track can we?

2017-06-20 14:34 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +                pc._dtmf = null;
either way i think the else is not necessary

2017-06-20 14:36 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +                pc._dtmf = null;
ah... and this is sender not pc. Thanks for explaining!

2017-06-20 15:36 UTC, fippo commented
I think i'm done. Only thing left before a big squash is making the dtmf test unskip-able -- i need to check the status in Edge and Safari for that.

2017-06-21 08:15 UTC, fippo commented
so Safari doesn't seem to do dtmf and  Edge needs a shim for sender.dtmf -- easy but not in this PR.

It might be possible to make this stuff simpler by polyfilling it on RTCRtpSender.prototype globally. But again, not this PR

2017-06-21 12:49 UTC, jan-ivar commented on src/js/chrome/chrome_shim.js
> +                pc._dtmf = null;
I guess that works. i.e. I guess `pc.createDTMFSender()` may be called more than once on the same `pc` with different tracks in Chrome? Might want to test that manually at least.

2017-06-21 12:52 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +                pc._dtmf = null;
i already reverted that, it was stupid and your stuff was better :-)

2017-06-21 13:02 UTC, henbos requested changes
I still have a feeling shimAddTrack doesn't have to be defined twice without complicated code, see other comments. Also consider the addStream/removeStream/getLocalStreams cases.

2017-06-21 13:02 UTC, henbos commented on src/js/chrome/chrome_shim.js
> +      return sender;
prepareSender(track) for the has getSender case could be lines 344-350 and here do return prepareSender(track);

2017-06-21 13:02 UTC, henbos commented on src/js/chrome/chrome_shim.js
> +      if (alreadyExists) {
findSender(track) for the has getSender case could be lines 322-324 and here if (findSender(track)).

2017-06-21 13:02 UTC, henbos commented on src/js/chrome/chrome_shim.js
>            return sender;
prepareSender(track) for the getSender missing case could be lines 145-147 and here return prepareSender(track).

2017-06-21 13:02 UTC, henbos commented on src/js/chrome/chrome_shim.js
>            if (alreadyExists) {
findSender(track) for the getSender missing case could be lines 122-124 and here if (findSender(track)).

2017-06-21 13:03 UTC, henbos commented on src/js/chrome/chrome_shim.js
>            if (alreadyExists) {
That is, if we define shimAddTrack once and use helper functions findSender and prepareSender that are defined differently whether or not we have getSenders.

2017-06-22 06:48 UTC, fippo commented
I can see where you want to go... basically shimming getSenders and then making the decisions in addStream depend on whether getSenders is available etc. This could work and eliminate the duplicated code. It will take another two weeks to get right at the current pace and the basic functionality that this PR is trying to fix has been reported as broken over a month ago.

2017-06-22 08:49 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +      if (alreadyExists) {
i'd rather do that with an arrow function once we can use them in ES6

2017-06-22 08:50 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +      var alreadyExists = pc.getSenders().find(function(s) {
note that now this shim relies on the shimGetSendersWithDtmf to be called later in order to provide getSenders(). Kind of weird but the tests prove it is working.

2017-06-22 11:43 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +      var alreadyExists = pc.getSenders().find(function(s) {
and I added an extra test just for getSenders

2017-06-27 13:06 UTC, henbos commented on src/js/chrome/chrome_shim.js
> +        return self._reverseStreams[stream.id];
Do you need to do pc._reverseStreams = pc._reverseStreams || {}; before the map() in case getLocalStreams() is the first function called and _reverseStreams is undefined?

2017-06-27 13:06 UTC, henbos commented on src/js/chrome/chrome_shim.js
> +        pc.addStream(newStream);
I was going to suggest marking newStream as an "addTrack-stream" so that in getLocalStreams() we don't include it, yielding:
pc.addTrack(track, stream);
pc.getLocalStreams().includes(stream); // false

But it looks like Firefox does add addTrack-streams to local streams which would make this correct, and it should be tested.

2017-06-27 13:06 UTC, henbos commented on test/test.js
> +          pc1.removeStream(stream);
Here and in other tests: Can you add a todo with a reference to #577 saying we should use removeTrack if available.

2017-06-27 13:06 UTC, henbos commented on test/test.js
> +    navigator.mediaDevices.getUserMedia({audio: true})
Can you add a test that makes sure a stream of an audio and video track and addTrack with one of them creates a single sender for that track alone? So that both are not added.

And a test that makes sure that multiple addTrack calls results in an exception (sender already exists).

2017-06-27 13:15 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +        return self._reverseStreams[stream.id];
why would anyone... but 👍

2017-06-27 13:17 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +        pc.addStream(newStream);
yes, we need more tests for this behaviour. In the new karma tests from #597 this will be much easier.

2017-06-27 13:18 UTC, fippo commented on test/test.js
> +    navigator.mediaDevices.getUserMedia({audio: true})
test('Basic connection establishment with addTrack ' +
    'and only the audio track of an av stream', function(t) {
-- this does a e2e test which ensure no stream is received at the remote end.

Multiple addTrack: yes, but in karma tests 'cause boilerplate ;-)

2017-06-27 13:20 UTC, fippo commented on test/test.js
> +          pc1.removeStream(stream);
added a note to the issue instead ;-)

2017-06-27 14:20 UTC, KaptenJansson commented
@henbos do you approve of @fippo's comments?

2017-06-27 14:30 UTC, henbos approved these changes

2017-06-27 14:33 UTC, KaptenJansson commented
LGTM

2017-06-27 14:33 UTC, merged