Use session ID for each peer connection on Edge
webrtcHacks/adapter pull request #587
Opened 2017-06-14 11:47 UTC by armouroflight

We have seen that the adapter.js currently uses the same hardcoded session ID for all SDP.  This makes it a random session ID for each RTCPeerConnection which is like other browsers have been seen to do.

This change relies on changes in sdp.js which I have put in a PR for.  Let me know if you need any more details.

2017-06-14 21:39 UTC, armouroflight commented
I signed it!

2017-06-15 08:26 UTC, fippo approved these changes
(wrong comment)

2017-06-15 08:26 UTC, fippo commented on package.json
> +    "sdp": "git://github.com/armouroflight/sdp.git#cc26d22"
i can publish a new minor version (in the 2.x line) for this. Will come back with an exact version.
This will be a major bump of the sdp package but its ok, the other parts are prepared for this.

2017-06-15 08:26 UTC, fippo commented on src/js/edge/rtcpeerconnection_shim.js
> +    var sdp = SDPUtils.writeSessionBoilerplate(this._sdpSessionId);
this also needs to be done at the beginning of createAnswer.

2017-06-15 08:27 UTC, fippo requested changes
LGTM but needs a different approach for the SDP package

2017-06-16 07:20 UTC, armouroflight commented on src/js/edge/rtcpeerconnection_shim.js
> +    var sdp = SDPUtils.writeSessionBoilerplate(this._sdpSessionId);
Done!

2017-06-16 07:24 UTC, armouroflight commented
Let me know if you still have issues!   Thanks!

2017-06-16 07:32 UTC, fippo approved these changes
LGTM, over to @KaptenJansson -- this is patch imo

2017-06-16 13:46 UTC, KaptenJansson commented
LGTM

2017-06-16 13:46 UTC, merged