test: fix lint mess
webrtcHacks/adapter pull request #603
Opened 2017-06-28 13:00 UTC by fippo

prelude to #602 which fixes the linter mess.

2017-06-28 13:38 UTC, fippo commented
*sigh* @KaptenJansson can you restart just the chrome-stable job please? webdriver seemed to hang, I could not reproduce locally

2017-06-30 08:18 UTC, KaptenJansson requested changes
LGTM with nit

2017-06-30 08:18 UTC, KaptenJansson commented on test/e2e/connection.js
> +  function negotiate(pc, otherpc) {
Shouldn't otherpc be camelCase?

2017-06-30 08:40 UTC, KaptenJansson approved these changes

2017-07-03 07:05 UTC, merged