test: add tests for addTrack
webrtcHacks/adapter pull request #610
Opened 2017-07-03 10:59 UTC by fippo

adds tests for addTrack which were promised during the review of #559

@henbos PTAL, do you want more tests?
@jan-ivar looks like you throw InvalidParameterError instead. Is that a known bug? We can soon mark that test as expected failure

2017-07-03 14:58 UTC, henbos requested changes
Loving these new tests!

2017-07-03 14:58 UTC, henbos commented on test/e2e/addTrack.js
> +        expect(localStreams).to.have.length(1);
To confirm, is this what Firefox does?
I would have expected getLocalStreams() to be unaffected by addTrack(). But if this is the case I might have to modify getLocalStreams(), perhaps to return every stream of every sender instead of a set of streams modified on add/removeStream() before shipping addTrack() in Chrome.

2017-07-03 14:58 UTC, henbos commented on test/e2e/addTrack.js
> +    });
Can you add a test that does...?
stream = audio and video
addTrack(stream.audio);
expect getLocalStreams() == 1, getSenders() == 1
addStream(stream);
expect getLocalStreams() == 1, getSenders() == 2

2017-07-03 14:58 UTC, henbos commented on test/e2e/addTrack.js
> +      });
Can you add a test that makes sure it also throws an exception on addTrack if a sender was already created with addStream?

2017-07-03 15:00 UTC, fippo commented on test/e2e/addTrack.js
> +        expect(localStreams).to.have.length(1);
clone the repo, checkout [the branch for this PR](https://help.github.com/articles/checking-out-pull-requests-locally/), setenv or export BROWSER=firefox and run npm test. Add console.log as desired, this is now super easy ;-)

2017-07-03 15:06 UTC, jan-ivar commented on test/e2e/addTrack.js
> +        expect(localStreams).to.have.length(1);
@henbos Yeah that's what Firefox does atm. I should double-check with @docfaraday what will happen with `getLocalStreams()` once we're done with transceivers.

2017-07-03 15:20 UTC, fippo commented on test/e2e/addTrack.js
> +    });
Nice one! This currently fails because I am not creating an internal stream for addStream streams (required by and done in #611)

Firefox throws here since it has already been added:
```
  describe('and addStream', () => {
    it('adds unadded tracks of a stream', () => {
      return navigator.mediaDevices.getUserMedia({audio: true, video: true})
      .then(stream => {
        pc.addTrack(stream.getTracks()[0], stream);
        const localStreams = pc.getLocalStreams();
        expect(localStreams).to.have.length(1);
        expect(pc.getSenders()).to.have.length(1);

        pc.addStream(stream);
        expect(pc.getLocalStreams()).to.have.length(1);
        expect(pc.getSenders()).to.have.length(2);
      });
    });
  });
```
I have a slight preference for the Firefox behaviour since we throw when calling addTrack with the same track twice in the spec

2017-07-03 15:41 UTC, henbos commented on test/e2e/addTrack.js
> +    });
Throwing because one of the tracks have been added when you addStream() makes sense too. We'll have to make sure it adds all or none of the tracks though so it doesn't fail halfway through adding tracks of a stream. This is achieved if getLocalStream() behaves as above (how Firefox works) and if addStream() checks if getLocalStreams() has the stream. That's a straight-forward implementation that makes sense.

2017-07-03 15:42 UTC, henbos commented on test/e2e/addTrack.js
> +    });
Just expect it to throw on addStream and we're good.

2017-07-03 16:07 UTC, fippo commented on test/e2e/addTrack.js
> +    });
so that should throw BUT pc.getSenders() should still be 1. Hrm... I think that can be achieved by calling addTrack with the [1] track and then calling addStream.

2017-07-03 16:24 UTC, henbos commented on test/e2e/addTrack.js
> +        expect(localStreams).to.have.length(1);
I filed https://crbug.com/738918

2017-07-03 17:07 UTC, henbos commented on test/e2e/addTrack.js
> +    });
Firefox polyfills, so it does not do an all-or-nothing, it just forEach track does addTrack(track, stream). Considering this is legacy, I'm ok with adopting that behavior.

2017-07-03 17:10 UTC, fippo commented on test/e2e/addTrack.js
> +    });
yes. We should should not do it if we ever decide to actually specify the behaviour (-:

2017-07-03 17:58 UTC, fippo commented on test/e2e/addTrack.js
> +    });
added a test which tests for the exception

2017-07-03 18:00 UTC, fippo commented on test/e2e/addTrack.js
> +      });
done

2017-07-03 18:01 UTC, fippo commented
squash and we're good? Need to add expectations for #609

2017-07-03 19:02 UTC, henbos approved these changes
LGTM

2017-07-03 19:50 UTC, jan-ivar commented
> @jan-ivar looks like you throw InvalidParameterError instead. Filed a bug for you. We can soon mark that test as expected failure

@fippo Thanks! BTW, shouldn't this be a WPT test as well?

2017-07-10 08:28 UTC, fippo commented
made a minor change to the chrome shim to make this not work:
```
pc.addTrack(stream.getTracks()[0], stream);
pc.addStream(stream)
```
moar tests ;-)

2017-07-10 11:03 UTC, merged