chrome: shim removeTrack
webrtcHacks/adapter pull request #611
Opened 2017-07-03 13:39 UTC by fippo

shims pc.removeTrack.

@henbos if you're bored... ;-)

2017-07-03 14:43 UTC, fippo commented
Firefox does not throw an error when removing a track that does not belong to the pc. Filed [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1377888) for @jan-ivar ;-)

2017-07-03 15:34 UTC, henbos requested changes
Looking good!

2017-07-03 15:34 UTC, henbos commented on src/js/chrome/chrome_shim.js
>        return;
This will also skip shimming removeTrack if addTrack already exists (is supported or has already been shimmed). The "shim addTrack when getSenders is is not available" case will shim addTrack but not removeTrack, see previous comment.

2017-07-03 15:34 UTC, henbos commented on src/js/chrome/chrome_shim.js
>        // shim addTrack when getSenders is not available.
What about shim removeTrack when getSenders is not available? If addTrack is shimmed here and it already exists in the later code, it will skip shimming removeTrack because it skips shimming both addTrack and removeTrack

2017-07-03 15:34 UTC, henbos commented on src/js/chrome/chrome_shim.js
> +    window.RTCPeerConnection.prototype.removeTrack = function(sender) {
Can you add a comment to say which case this applies too, i.e. "when getSenders is available". If this should apply to both cases, make sure this doesn't abort in that case (see previous comments) and say in the comment that it applies to both.

2017-07-03 15:34 UTC, henbos commented on src/js/chrome/chrome_shim.js
> +      var stream;
let stream = null;

2017-07-03 15:34 UTC, henbos commented on src/js/chrome/chrome_shim.js
> +      });
if (stream == null) skip the removeStream/removeTrack step, but still dispatch a negotiationneeded event...
Hmh, It would seem silly to fire an negotiationneeded event if nothing changed, but that seems to be what the spec suggests. Perhaps do skip it and file a spec bug not to fire the event if the sender was already inactive? I'm guessing that's a spec bug.

2017-07-03 15:34 UTC, henbos commented on src/js/chrome/chrome_shim.js
> +            'InvalidAccessError');
The correct behavior when removing a track is to make the sender inactive, but not to remove it. We (both adapter and chrome) remove senders that are no longer used, and this I think we should continue to do until we have transceiver support.

But a side-effect is that this is not a reliable way to check if the sender was created by this connection. If you remove the same sender twice the second will throw an exception instead of be a NO-OP. I would rather skip throwing an exception if you use another PC's sender than to have it throw an exception if you remove an already removed sender since this should be a more common use case.

2017-07-03 15:34 UTC, henbos commented on test/e2e/removeTrack.js
> +      });
Add a test that makes sure it is OK to do removeTrack twice.

2017-07-03 15:34 UTC, henbos commented on test/e2e/removeTrack.js
> +      beforeEach(() => {
beforeEach... Awesome testing tools 👍

2017-07-03 16:03 UTC, fippo commented on src/js/chrome/chrome_shim.js
>        // shim addTrack when getSenders is not available.
shimGetSendersWithDtmf is called after this. The comment is a bit misleading now, thanks for catching that!

2017-07-03 16:03 UTC, fippo commented on src/js/chrome/chrome_shim.js
>        return;
see above. Do you intend to ship addTrack without removeTrack (you can probably ship but i would not do so unflagged)
The behaviour of both shims is heavily intertwined, i don't think it makes much sense to untangle them.

2017-07-03 16:03 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +    window.RTCPeerConnection.prototype.removeTrack = function(sender) {
uh... I think you caught a missing removeTrack shim that cleans up the _senders stuff!

2017-07-03 16:03 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +      });
I discussed with @jan-ivar a few days ago and... https://github.com/w3c/webrtc-pc/pull/1434 ;-)
Now need to dogfood too

2017-07-03 16:03 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +            'InvalidAccessError');
Right. Ideally we would set sender.track = null but I don't think we can control the behaviour enough to be spec-compliant.

2017-07-03 16:03 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +            'InvalidAccessError');
What is the use-case here -- holding on to the result of pc.getSenders()? I hope people don't do that

2017-07-03 19:53 UTC, jan-ivar commented
> Firefox does not throw an error when removing a track that does not belong to the pc. 

@fippo Thanks! Again it'd be nice if this were a WPT tests as well I think...

2017-07-03 20:03 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +    window.RTCPeerConnection.prototype.removeTrack = function(sender) {
it wasn't missing but _senders was called in the addTrackRemoveTrack shim -- and it should have been called in the getSendersWithDtmf shim. Moved there

2017-07-04 14:27 UTC, henbos commented on src/js/chrome/chrome_shim.js
>        return;
No that's fine, as long as that assumption is clear with a comment. addTrack and removeTrack will be shipped at the same time.

2017-07-04 14:27 UTC, henbos commented on src/js/chrome/chrome_shim.js
> +            'InvalidAccessError');
Yes, as of now you would only hit this problem if you held on to senders (getSenders() or addTrack() return values, maybe the app has its own map for some reason) after being removed. It's also possible that a rollback happens in which case a sender is no longer used.

If getSenders() is updated you could get inactive senders too, someone might write "remove all tracks" code that just loops through all senders and does remove, including already inactive senders. That could work now but break later if this throws and exception and transceivers are implemented.

2017-07-04 14:35 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +            'InvalidAccessError');
right. But you plan to ship the real thing way ahead of that (and also really soon now?) and then cruft won't be necessary anymore?

2017-07-08 12:41 UTC, fippo commented on test/e2e/removeTrack.js
> +      });
done. Changed the logic a bit so that each sender has a ._pc

2017-07-10 10:23 UTC, henbos approved these changes
LGTM % comments

2017-07-10 10:23 UTC, henbos commented on src/js/chrome/chrome_shim.js
> +          pc._senders.splice(pc._senders.indexOf(sender), 1);
If you removeTrack with a sender that does not exist this will remove the last item of _senders. Make sure indexOf(sender) is not -1.

2017-07-10 10:23 UTC, henbos commented on src/js/chrome/chrome_shim.js
> +        var origRemoveTrack = window.RTCPeerConnection.prototype.removeTrack;
You're relying on addTrack and removeTrack existing. This is only guaranteed if chromeShim.shimAddTrackRemoveTrack has been called prior. Can you make this assumption explicit with a comment and throwing an exception that shim failed if that isn't the case?

2017-07-10 10:38 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +        var origRemoveTrack = window.RTCPeerConnection.prototype.removeTrack;
added a comment. I don't think we need to explicitly throw but should test once you unflag the native variants

2017-07-10 13:45 UTC, merged