chrome: munge sdp to keep stream ids
webrtcHacks/adapter pull request #637
Opened 2017-07-24 08:10 UTC by fippo

munges the SDP in createOffer, createAnswer and setLocalDescription as well
as the pc.localDescription accessor in order to retain the stream ids that
are modifed by the addTrack shim.

Fixes #634 

@henbos can you take a look? I tried to mangle the getStats result too but that didn't work :-/

2017-07-24 13:06 UTC, henbos commented
Shimming getStats didn't work? Isn't the only thing that needs to be updated RTCMediaStreamStats.streamIdentifiers and RTCMediaStreamTrackStats.trackIdentifier?

2017-07-24 13:53 UTC, fippo commented
tracks are kept the same ;-)
I had a patch that did this:
```
-    // TODO: mangle getStats: https://w3c.github.io/webrtc-stats/#dom-rtcmediastreamstats-streamidentifier
+    var origGetStats = window.RTCPeerConnection.prototype.getStats;
+    window.RTCPeerConnection.prototype.getStats = function() {
+      var pc = this;
+      return origGetStats.apply(pc, arguments)
+      .then(function(result) {
+        result.forEach(function(stat) {
+          if (stat.type === 'stream' && pc._reverseStreams) {
+            var externalStream = pc._reverseStreams[stat.streamIdentifier];
+            if (externalStream) {
+              stat.streamIdentifier = externalStream.id;
+            }
+          }
+        });
+        return result;
+      });
+    };
```
It seemed to work but magically in the next function the streamIdentifier was the old string again.

2017-07-24 14:31 UTC, henbos commented
Maybe another shimming of getStats overwrites that shimming?

2017-07-24 14:38 UTC, fippo commented
nah, I iterated again with another forEach before the "return result". Check here:
    https://jsfiddle.net/jfoe1L7g/
Really really odd...

2017-07-24 15:25 UTC, henbos commented
Oh, the stats objects are dictionaries, so they are returned as copies. Once returned you can modify them, but because the RTCStatsReport is a Maplike interface, every time you retrieve an element you get a copy of the original. In order to mangle this you need to mangle `result`. I think `Map` is a `Maplike`? If so you can just add all the modified members to a `new Map()` and return that.

2017-07-24 15:28 UTC, henbos commented
https://jsfiddle.net/s9goLhbp/1/

2017-07-28 18:16 UTC, markandrus commented
Any ETA/pre-reqs for landing this? The only workaround I could see was pulling copies of `addStream` and `removeStream` off a "fresh" RTCPeerConnection `prototype` from an &lt;iframe&gt;, but I really don't want to land such a workaround in my code...

2017-08-07 09:57 UTC, KaptenJansson commented
@henbos could you take a look at the latest commit?

2017-08-07 10:52 UTC, fippo commented
test failures in beta with experimental flag is real now... @henbos we need to have a fig.. err friendly chat ;-)

2017-08-19 07:16 UTC, fippo commented
@jan-ivar can you take a look at https://github.com/webrtc/adapter/pull/637/commits/466e3f651d306dbb59734421887eba99920f2396 please? I noticed that createOffer(cb, err, opts) resolved the promise with no arguments which lead to a very very confusing error.

2017-08-19 15:54 UTC, jan-ivar commented
@fippo I'd say leave legacy code alone, so we A) don't break it and B) leave the pearls for migraters.

The legacy callback methods] return `Promise<void>` [per spec](https://w3c.github.io/webrtc-pc/#legacy-interface-extensions) due to webidl overloading limitations.

2017-08-21 13:12 UTC, jan-ivar requested changes

2017-08-21 13:12 UTC, jan-ivar commented on src/js/chrome/chrome_shim.js
> +        return nativeMethod.apply(pc, [opts])
So this diverts calls of the legacy callback API to the promise API, which I don't like, as it will suppress native deprecation warnings (like in Firefox), and may also skew any telemetry of how many still call the legacy API. How about:
```js
var p, isLegacyCall = arguments.length && typeof arguments[0] === 'function';
if (isLegacyCall) {
  p = new Promise((r, e) => nativeMethod.apply(pc, [r, e, arguments[2]]));
} else {
  p = nativeMethod.apply(pc, arguments);
}
```
?

2017-08-21 13:12 UTC, jan-ivar commented on src/js/chrome/chrome_shim.js
> +        }, function(err) {
You're not catching any potential programming errors in this code. I'd change `.then(a, b)` to `.then(a).catch(b)`.

2017-08-21 13:12 UTC, jan-ivar commented on src/js/chrome/chrome_shim.js
> +            return Promise.resolve();
redundant. Just `return;` will do

2017-08-21 13:12 UTC, jan-ivar commented on src/js/chrome/chrome_shim.js
> +          }
`} else { throw err; }` otherwise you're removing errors for promise-users.

2017-08-21 18:16 UTC, jan-ivar requested changes

2017-08-21 18:16 UTC, jan-ivar commented on src/js/chrome/chrome_shim.js
>              sdp: sdp
I think you meant to call `replaceInternalStreamId()` here.

2017-08-21 18:16 UTC, jan-ivar commented on src/js/chrome/chrome_shim.js
> +        sdp: replaceExternalStreamId(pc, arguments[0].sdp)
We might want to wrap this in
```js
if (arguments[0].type || typeof arguments[0].sdp === 'string')
```
to protect this polyfill from bogus input without having to mimic native error checking.

2017-08-21 18:32 UTC, fippo commented on src/js/chrome/chrome_shim.js
>              sdp: sdp
no, we take the external stream id in the SDP (which comes from createOffer/createAnswer usually) and replace it with the internal one before SLD. I agree that the naming is suboptimal, but its two different operations

2017-08-21 18:36 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +        sdp: replaceExternalStreamId(pc, arguments[0].sdp)
👍 -- I didn't check for .sdp because rollbacks

2017-08-24 08:18 UTC, KaptenJansson commented
@henbos could you take another look?

2017-08-24 17:51 UTC, henbos requested changes
Looking good.

2017-08-24 17:51 UTC, henbos commented on src/js/chrome/chrome_shim.js
> +      return origSetLocalDescription.apply(pc, [desc]);
Can you instead of "var desc = ..." do "arguments[0] = ..." and then do "origSetLocalDescription.apply(pc, arguments)" and get rid of the isLegacyCall check?

2017-08-24 17:51 UTC, henbos commented on src/js/chrome/chrome_shim.js
> +        var args = arguments;
No need for "args", simply use "arguments".

2017-08-24 17:51 UTC, henbos commented on src/js/chrome/chrome_shim.js
> +    }
Every call to replaceInternal/ExternalStreamId is in a "new window.RTCSessionDescription". If you make these functions do that bit too you reduce a few repeated lines of code in the rest of the file.

2017-08-24 17:51 UTC, henbos commented on src/js/chrome/chrome_shim.js
> +    // TODO: mangle getStats: https://w3c.github.io/webrtc-stats/#dom-rtcmediastreamstats-streamidentifier
Do you want to do this separately? https://jsfiddle.net/s9goLhbp/1/

2017-08-24 17:51 UTC, henbos commented on test/e2e/msid.js
> +  });
Add a test that verifies "localDescription" is what you expect.

2017-08-24 18:13 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +        var args = arguments;
no, args is used in the legacy case. Can't use arguments there since that is a different function scope

2017-08-24 18:13 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +      return origSetLocalDescription.apply(pc, [desc]);
sneaky...

2017-08-24 18:15 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +    // TODO: mangle getStats: https://w3c.github.io/webrtc-stats/#dom-rtcmediastreamstats-streamidentifier
yeah, different PR

2017-08-24 18:17 UTC, fippo commented on test/e2e/msid.js
> +  });
A test for accessing .localDescription is indeed missing. Can I add this later? I promise ;-)

2017-08-25 11:00 UTC, henbos approved these changes
LGTM

2017-08-25 11:00 UTC, henbos commented on src/js/chrome/chrome_shim.js
> +        var args = arguments;
Acknowledged.

2017-08-25 11:00 UTC, henbos commented on test/e2e/msid.js
> +  });
If so can you create a bug or add a TODO?

2017-08-28 08:00 UTC, KaptenJansson approved these changes

2017-08-28 08:00 UTC, merged