common: make URL.createObjectURL shim depend on native support
webrtcHacks/adapter pull request #644
Opened 2017-08-09 05:35 UTC by fippo

fixes #569

2017-08-21 16:25 UTC, jan-ivar requested changes

2017-08-21 16:25 UTC, jan-ivar commented on src/js/utils.js
>      var nativeRevokeObjectURL = URL.revokeObjectURL.bind(URL);
This still calls `undefined.bind()`. Better to test for 
```js
if (!URL.createObjectURL || !URL.revokeObjectURL)
```

2017-08-21 16:31 UTC, fippo commented on src/js/utils.js
>      var nativeRevokeObjectURL = URL.revokeObjectURL.bind(URL);
moved up a bit, thanks for suggesting this!

2017-08-24 09:05 UTC, KaptenJansson approved these changes

2017-08-24 09:05 UTC, merged