Safari bits offer options
webrtcHacks/adapter pull request #786
Opened 2018-03-07 17:49 UTC by zaxy78

Fix for #785 + unit tests for legacy createOffer shim

2018-03-08 09:18 UTC, KaptenJansson requested changes

2018-03-08 09:18 UTC, KaptenJansson commented on src/js/safari/safari_shim.js
> +        var isBit = offerOptions.offerToReceiveAudio;
Since you are using it in two places and its quite a few lines, perhaps pull it out to a helper function instead?

2018-03-08 11:48 UTC, zaxy78 commented on src/js/safari/safari_shim.js
> +        pc.offerToReceiveVideo = !!pc.offerToReceiveVideo; // support bit value
found a much simpler way to fix this. 
but gave up the 'deprecation' message I've put there.

2018-03-08 12:00 UTC, zaxy78 commented on src/js/safari/safari_shim.js
> +        offerOptions.offerToReceiveVideo = !!offerOptions.offerToReceiveVideo;
@KaptenJansson - I found a much simpler way to fix this.
but gave up the 'deprecation' message I've put there.

2018-03-08 12:26 UTC, fippo commented on src/js/safari/safari_shim.js
> +        offerOptions.offerToReceiveVideo = !!offerOptions.offerToReceiveVideo;
if offerToReceiveVideo is unset the !! will make it false which may change the direction. The simplest way might be to check for "this isn't undefined"

2018-03-08 13:31 UTC, zaxy78 commented
@KaptenJansson looks better?

2018-03-08 13:32 UTC, zaxy78 commented on src/js/safari/safari_shim.js
> +        }
@KaptenJansson looks better?

2018-03-13 08:21 UTC, KaptenJansson requested changes

2018-03-13 08:21 UTC, KaptenJansson commented on src/js/safari/safari_shim.js
> +        if (offerOptions.offerToReceiveAudio !== undefined) {
I would prefer typeof instead even though its not used everywhere in this repo.

`if (typeof offerOptions.offerToReceiveVideo !== 'undefined') {
.... }`

2018-03-13 12:40 UTC, zaxy78 commented on src/js/safari/safari_shim.js
> +        if (offerOptions.offerToReceiveAudio !== undefined) {
@KaptenJansson  done

2018-03-15 13:51 UTC, zaxy78 commented
Fixed and Ready to merge.

Also, @KaptenJansson, when do you plan to have the next release?

I think after #783, we can add "Support for iOS WKWebView" and make a new release

2018-03-24 18:14 UTC, zaxy78 commented
@KaptenJansson, thanks for the release publish. any reason not to merge this?
I fixed your comments..

2018-03-26 13:58 UTC, KaptenJansson approved these changes

2018-03-26 13:58 UTC, merged