ensure shim’s name property matches original function
webrtcHacks/adapter pull request #978
Opened 2019-06-17 21:44 UTC by cam-narzt

**Description**
Adds function names to shim functions at point of definition.

**Purpose**
This is just a small change to make the shims act a little more like the original functions. As is if you call `RTCIceCandidate.name` on an unshimmed `RTCIceCandidate`, you get the string `"RTCIceCandidate"` but on a shimmed one you get `""`.

2019-06-17 21:48 UTC, cam-narzt commented
The patch was generated with this command: 
`rg 'window(\.|\[).*=.*function *\(' -l src/ | xargs -n1 -I{} sed -i '' -Ee 's/(.*\.([^\.[:space:]]+)[[:space:]]=)(.*)(function) *\(/\1\3\4 \2\(/g' {}`

Documentation on the name property: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name

I admit to not having tested this locally, as I wanted to get feedback before spending too much time on this. I ran into the difference in behaviour while writing a tracing proxy of the WebRTC API functions to make sure my tests accurately reflect real browser behaviour.

2019-06-23 11:50 UTC, fippo commented
There are some ```function prototype[method]()``` which the linter doesn't like, otherwise this looks good to me. It increases readability of stack traces, right?

2019-06-23 16:05 UTC, CamJN commented
Yeah, it helps with stack traces, as well as any debugging/tracing libraries you may be using.

2019-06-23 16:07 UTC, cam-narzt commented
Yeah, it helps with stack traces, as well as any debugging/tracing libraries you may be using. 

(Sorry for the double post, used the wrong account).

2019-06-24 15:25 UTC, fippo requested changes

2019-06-24 15:25 UTC, fippo commented on src/js/chrome/chrome_shim.js
> +          window.RTCPeerConnection.prototype[method] = function prototype[method]() {
this breaks (a couple of times). Not sure if it makes sense to "unroll" this (and other) loop in order to ease debugging

2019-06-25 01:21 UTC, cam-narzt commented on src/js/chrome/chrome_shim.js
> +          window.RTCPeerConnection.prototype[method] = function prototype[method]() {
I pushed a change to fix this to real syntax, but I'm not sure if it will actually set the function name property, so it's a bit of an experiment.

2019-06-27 15:33 UTC, fippo commented
now the linter complaints about line length and a couple of variable name conflict in the safari shim. Its probably best to rename the variables to origSomething as its done elsewhere.

2019-07-03 08:31 UTC, fippo commented
git diff -w to the rescue. Nice way of dealing with the iterated methods!
Will go into next release (hopefully this week)

Thank you!

2019-07-03 08:32 UTC, fippo approved these changes

2019-07-03 08:32 UTC, merged